### ISSUE TITLE
getViewportMedia(): Let pages opt-in to capture

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-viewport#1]
Compared to native, capturing a web page has been plagued by [security concerns](https://blog.mozilla.org/webrtc/share-browser-windows-entire-screen-sites-trust/) since this spec's inception. Can we imagine a web that's safer to screen-capture, similar to a [web where `SharedArrayBuffer` is safer to use](https://web.dev/why-coop-coep/#coep)?

What if we came across a page that met these conditions? We could remove restrictions added for the legacy web, both for some choices in the existing `getDisplayMedia` and new APIs like the proposed ~`getTabMedia`~ `getViewportMedia`.

One idea for such opt-in is `Cross-Origin-Embedder-Policy: require-corp; html-capture` covered in slides [here](https://docs.google.com/presentation/d/1CeNeno5XuDhm1mpnVyE9eT14YKZgZUtgQsJfC8uqEpA/edit?ts=5fc7fcd2#slide=id.g786a1abc5c_1_94).

I'm opening an issue to discuss this independent of those APIs. Note it only covers the cross-origin issue. Permissions are still needed to cover user information harvesting.

I've also created a [COEP playground](https://marvelous-interesting-vessel.glitch.me/require-corp
) in glitch ([[1]](https://glitch.com/edit/#!/marvelous-interesting-vessel?path=test.html%3A1%3A0), [[2]](https://glitch.com/edit/#!/complex-fate-zone?path=server.js%3A3%3A0)) for those unfamiliar with the concept and want to experiment with it.

**Comment by jan-ivar** [comment]
@camillelamy @annevk Note, the WG went with `viewport-capture` for document policy name. See https://github.com/w3c/mediacapture-viewport/pull/4. If you feel strongly about `html-capture` let us know, and we can raise it again on Tuesday.

**Comment by annevk** [comment]
I don't care particularly strongly. What's not entirely clear to me is whether Document Policy is still something Google is pursuing. E.g., https://github.com/w3c/webappsec-permissions-policy/issues/444#issuecomment-1049592853 does not inspire much confidence.

**Comment by camillelamy** [comment]
I am ok with the new name. Required Document Policy is something we are interested in pursuing, provided there is some use case that requires it. Capture could be such a use case. In particular, we do believe that the mechanism could potentially be useful for security checks like opt into tab capture, but it may be true that it is less useful for performance optimizations.
