### ISSUE TITLE
Remove DisplayMediaStreamConstraints use

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-viewport#23]
DisplayMediaStreamConstraints has been removed from screen share spec.
We should have a ViewPortCaptureMediaStreamOptions instead of reusing/extending DisplayMediaStreamConstraints.

**Comment by dontcallmedom** [comment]
dup of #21 (for which #22 is pending)

**Comment by alvestrand** [comment]
The screen share renamed it, it did not remove it. We should switch to using the new name, not start inventing new stuff.

**Comment by dontcallmedom** [comment]
I don't think the options in `DisplayMediaStreamOptions` such as `surfaceSwitching` or `selfBrowserSurface` makes sense in the context of `getViewportMedia`, so using a dedicated dictionary as suggested in #22 seems preferable.
